version: '3.7'

services:
  nginx:
    container_name: cp_partner_admin_front_nginx
    image: nginx:alpine
    working_dir: /app/build
    volumes:
      - build:/app
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - ${REACT_APP_PORT}:80
    command: sh -c "nginx -g 'daemon off;'"

  node:
    container_name: cp_partner_admin_frontfront__node
    image: node:14.16.1-alpine
    working_dir: /app
    volumes:
      - .:/app
      - build:/app/build
      - /app/node_modules
    command: sh -c "npm i && npm run build"

volumes:
  build:
