version: "3.7"

services:
  node:
    container_name: vite_react_template_base
    tty: true
    stdin_open: true
    image: node:14.16.1-alpine
    working_dir: /app
    volumes:
      - ./src:/app
    ports:
      - "8090:3000"
    command: sh -c "npm i && npm run dev"
